services:
  - type: web
    name: alton-portfolio-api
    plan: free
    runtime: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: SESSION_COOKIE_SECURE
        value: "False"
      - key: CSRF_COOKIE_SECURE
        value: "False"
      - key: DATABASE_URL
        sync: false
