# Generated by Django 6.0.8 on 2026-09-13 09:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('icon', models.CharField(help_text='Emoji or icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('items', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100})}, help_text='List of sub-services.')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.CharField(default='/chat', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(default='Chat with my AI', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='I build AI systems, interactive dashboards, and digital tools for education and development.', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default="Hi, I'm Alton Kesselly.", max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rotating_roles',
            field=wagtail.fields.StreamField([('role', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100})}, help_text='Roles that cycle in the hero typing animation.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats',
            field=wagtail.fields.StreamField([('stat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {})}, help_text='Stat cards shown under the hero.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trusted_by',
            field=wagtail.fields.StreamField([('logo', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1)]], {})}, help_text="Organizations or institutions you've worked with."),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.TextField(max_length=300)),
                ('author', models.CharField(default='Alton Kesselly', max_length=100)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Minutes')),
                ('category', models.CharField(default='AI & Education', max_length=50)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('code', 5), ('quote', 6)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4)]], {'icon': 'code'}), 6: ('wagtail.blocks.BlockQuoteBlock', (), {})})),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog Post',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LecturePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(max_length=500)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration', models.CharField(help_text="e.g. '4h 30m'", max_length=50)),
                ('lesson_count', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, help_text='YouTube / Vimeo embed URL')),
                ('syllabus_url', models.URLField(blank=True)),
                ('lessons', wagtail.fields.StreamField([('lesson', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. '12 min'", 'max_length': 20}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('duration', 1), ('video_url', 2)]], {})})),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Lecture',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(help_text='Short summary for cards.', max_length=500)),
                ('category', models.CharField(choices=[('ai_ml', 'AI & Machine Learning'), ('dashboard', 'Data & Dashboards'), ('software', 'Software Engineering'), ('education', 'Education & Policy'), ('research', 'Research & Analysis'), ('teaching', 'Teaching & Tutorials')], default='software', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage grid.')),
                ('live_demo_url', models.URLField(blank=True)),
                ('case_study_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('tech_stack', wagtail.fields.StreamField([('tech', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'python', 'react'", 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('icon', 1)]], {})})),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('code', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 20}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('language', 3), ('code', 4)]], {'icon': 'code'})}, help_text='Full case study content.')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Project',
            },
            bases=('wagtailcore.page',),
        ),
    ]
