# Generated by Django 6.1.1 on 2026-09-13 21:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_service_alter_homepage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturepage",
            name="resources",
            field=wagtail.fields.StreamField(
                [("document", 3), ("link", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 300, "required": False},
                    ),
                    2: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("document", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 1), ("url", 4)]],
                        {},
                    ),
                },
                help_text="Upload PDFs, Word docs, spreadsheets, presentations, or link to external resources (Google Docs, Sheets, Slides, etc.).",
            ),
        ),
    ]
