# Generated by Django 6.0.8 on 2026-09-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Anonymous ID to group messages from the same visitor.', max_length=100)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('page_context', models.CharField(blank=True, help_text='Which page the visitor was on when they chatted.', max_length=200)),
                ('flagged', models.BooleanField(default=False, help_text='Mark for review (e.g., bad answer, missing info).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Chat Log',
                'verbose_name_plural': 'AI Chat Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
